services:
  - type: web
    plan: free
    name: Pbxnew
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash setup
    repo: https://github.com/Badhacker98/PBX_2.0
    branch: master
    autoDeploy: False
    envVars:
      key: MINIO_PASSWORD
  fromService:
    name: minio
    type: pserv
    envVarKey: MINIO_ROOT_PASSWORD
