services:
  - type: web
    plan: free
    name: Pbxnew
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash setup
    repo: https://github.com/Badhacker98/PBX_2.0
    branch: master
    autoDeploy: False
    envVars:
    - key: BOT_TOKEN
      value: https://api.example.com      
     - key: BOT_TOKEN2
      sync: false
       
        
